apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "berkshire-agent.fullname" . }}-config
  namespace: {{ include "berkshire-agent.namespace" . }}
  labels:
    {{- include "berkshire-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | default "" | indent 4 }}
